{
	"version": 1730358853,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/nessupermariobrosworld3-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tilemap.png",
		"images/nessupermariobrosworld-sheet0.png",
		"images/daun-sheet0.png",
		"images/daun-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/platformstage2.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/bgstage22.png",
		"images/detail.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/spritefont.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite30-sheet1.png",
		"images/charaspawn-sheet0.png",
		"images/tilemap2.png",
		"images/tilemap4.png",
		"images/sprite32-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite35-sheet1.png",
		"images/sprite35-sheet2.png",
		"images/sprite36-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite40-sheet1.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite42-sheet1.png",
		"images/sprite43-sheet0.png",
		"images/sprite43-sheet1.png",
		"images/sprite44-sheet0.png",
		"images/sprite44-sheet1.png",
		"images/sprite45-sheet0.png",
		"images/sprite46-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/sprite48-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite51-sheet0.png",
		"images/sprite52-sheet0.png",
		"media/yt1s.com - undertale ost 014  heartache.m4a",
		"media/yt1s.com - undertale ost 014  heartache.ogg",
		"media/yt1scom-sword-slash-sound-effects-mani-creation_jeajxhvk.m4a",
		"media/yt1scom-sword-slash-sound-effects-mani-creation_jeajxhvk.ogg",
		"media/yt1s.com - 全ての人の魂の戦い ush ver.m4a",
		"media/yt1s.com - 全ての人の魂の戦い ush ver.ogg",
		"media/pedang kena.m4a",
		"media/pedang kena.ogg",
		"media/yt1s (mp3cut.net).m4a",
		"media/yt1s (mp3cut.net).ogg",
		"media/ffiostlich&krakenbossthemes(bossbattlea).m4a",
		"media/ffiostlich&krakenbossthemes(bossbattlea).ogg",
		"media/serang.m4a",
		"media/serang.ogg",
		"media/kena hit.m4a",
		"media/kena hit.ogg",
		"media/hehh.m4a",
		"media/hehh.ogg",
		"media/mati.m4a",
		"media/mati.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}